/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXReceiver,
  IXReceiverInterface,
} from "../../../../@connext/interfaces/core/IXReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_transferId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "_originSender",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "_origin",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "_callData",
        type: "bytes",
      },
    ],
    name: "xReceive",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IXReceiverInterface {
    return new Interface(_abi) as IXReceiverInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IXReceiver {
    return new Contract(address, _abi, runner) as unknown as IXReceiver;
  }
}
